// USER

// Fetch All Users
export const REQUEST_ALL_USERS = 'REQUEST_ALL_USERS';
export const RECEIVE_ALL_USERS = 'RECEIVE_ALL_USERS';
// Fetch Single User
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
// Create User Actions
export const REQUEST_CREATE_USER = 'REQUEST_CREATE_USER';
export const RECEIVE_CREATED_USER_RESPONSE = 'RECEIVE_CREATED_USER_RESPONSE';
export const RECEIVE_CREATED_USER_SUCCESS = 'RECEIVE_CREATED_USER_SUCCESS';
// Signin Actions
export const REQUEST_SIGNIN = 'REQUEST_SIGNIN';
export const RECEIVE_SIGNIN_RESPONSE = 'RECEIVE_SIGNIN_RESPONSE';
export const RESET_SIGNIN_ERRORS = 'RESET_SIGNIN_ERRORS';
// Fetch Current User's Overtime & Dayoff
export const REQUEST_CURRENT_USER_DATA = 'REQUEST_CURRENT_USER_DATA';
export const RECEIVE_CURRENT_USER_DATA = 'RECEIVE_CURRENT_USER_DATA';
//------------------------------------------------------------------------
// OVERTIME
// Fetch All Overtimes
export const REQUEST_CURRENT_USER_OVERTIMES = 'REQUEST_CURRENT_USER_OVERTIMES';
export const RECEIVE_CURRENT_USER_OVERTIMES = 'RECEIVE_CURRENT_USER_OVERTIMES';
// Create Overtime
export const REQUEST_CREATE_OVERTIME = 'REQUEST_CREATE_OVERTIME';
export const RECEIVE_CREATED_OVERTIME_RESPONSE =
  'RECEIVE_CREATED_OVERTIME_RESPONSE';
export const RECEIVE_CREATED_OVERTIME_SUCCESS =
  'RECEIVE_CREATED_OVERTIME_SUCCESS';
// Delete Overtime
export const REQUEST_DELETE_OVERTIME = 'REQUEST_DELETE_OVERTIME';
export const RECEIVE_DELETED_OVERTIME_RESPONSE =
  'RECEIVE_DELETED_OVERTIME_RESPONSE';
export const RECEIVE_DELETED_OVERTIME_SUCCESS =
  'RECEIVE_DELETED_OVERTIME_SUCCESS';
// Update Overtime
export const REQUEST_UPDATE_OVERTIME = 'REQUEST_UPDATE_OVERTIME';
export const RECEIVE_UPDATED_OVERTIME_RESPONSE =
  'RECEIVE_UPDATED_OVERTIME_RESPONSE';
export const RECEIVE_UPDATED_OVERTIME_SUCCESS =
  'RECEIVE_UPDATED_OVERTIME_SUCCESS';

//------------------------------------------------------------------------
// DAYOFF
export const ADD_DAYOFF = 'ADD_DAYOFF';
export const DELETE_DAYOFF = 'DELETE_DAYOFF';
export const UPDATE_DAYOFF = 'UPDATE_DAYOFF';
export const GET_DAYOFFS = 'GET_DAYOFFS';

//------------------------------------------------------------------------
// GENERAL
export const RECEIVE_API_REQUEST_FAILURE = 'RECEIVE_API_REQUEST_FAILURE';
