// USER
// Fetch All Users
export const REQUEST_ALL_USERS = 'REQUEST_ALL_USERS';
export const RECEIVE_ALL_USERS = 'RECEIVE_ALL_USERS';

// Fetch Single User
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

// Create User Actions
export const REQUEST_CREATE_USER = 'REQUEST_CREATE_USER';
export const RECEIVE_CREATED_USER_RESPONSE = 'RECEIVE_CREATED_USER_RESPONSE';
export const RECEIVE_CREATED_USER_SUCCESS = 'RECEIVE_CREATED_USER_SUCCESS';

// Signin Actions
export const REQUEST_SIGNIN = 'REQUEST_SIGNIN';
export const RECEIVE_SIGNIN_RESPONSE = 'RECEIVE_SIGNIN_RESPONSE';
export const RECEIVE_SIGNIN_SUCCESS = 'RECEIVE_SIGNIN_SUCCESS';

//------------------------------------------------------------------------
// DAYOFF
export const ADD_DAYOFF = 'ADD_DAYOFF';
export const DELETE_DAYOFF = 'DELETE_DAYOFF';
export const UPDATE_DAYOFF = 'UPDATE_DAYOFF';
export const GET_DAYOFFS = 'GET_DAYOFFS';

// OVERTIME
export const ADD_OVERTIME = 'ADD_OVERTIME';
export const DELETE_OVERTIME = 'DELETE_OVERTIME';
export const UPDATE_OVERTIME = 'UPDATE_OVERTIME';
export const GET_OVERTIMES = 'GET_OVERTIMES';

// GENERAL
export const RECEIVE_API_REQUEST_FAILURE = 'RECEIVE_API_REQUEST_FAILURE';
